import Head from 'next/head';
import Link from 'next/link';

import styles from '../styles/Home.module.css';

export default function Home({ author }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cinema</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Sobre o sistema</h1>
        <p>
          O sistema foi feito em live para demonstrar os primeiros passos com o
          framework Next.js
        </p>
        <hr/>
        Autor: {author}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      author: "Lucas Furtado",
    },
  };
}
